import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | New Welcome"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-gray-800 text-white p-4">
          <nav className="container flex justify-center mx-auto">
            <ul className="flex space-x-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/products">Product</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/login">Login</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        
        <footer className="bg-gray-800 text-white p-4 text-center">
          <p> &copy; Ami Nijei 2025</p>
        </footer>
      </body>
    </html>
  );
}
