import Link from 'next/link'
import React from 'react'

export const metadata = {
  title: "Product Page",
  description: "Generated by create next app",
}
const ProductPage = () => {
  const productId = 100
  return (
    <div>
        <h1>ProductPage</h1>
        <h2><Link href="products/1">ProductPage1</Link></h2>
        <h3><Link href="products/2">ProductPage2</Link></h3>
        <h3><Link href="products/3" replace >ProductPage3</Link></h3>
        <h3><Link href={`products/${productId}`}>Product{productId}</Link></h3>
    </div>
  )
}

export default ProductPage